artifacts_root: artifacts

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_url: "https://github.com/syedowais57/DATASET-REPOSITORY/raw/main/archive%20(9).zip"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"
